name: Docker CI/CD Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub (⚠️ hardcoded for testing only)
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t srdeveloper9081/orthopedic-ai-app:latest1 .
        
     # 4️⃣ Scan Docker image with Trivy
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: srdeveloper9081/orthopedic-ai-app:latest1
          format: 'table'
          exit-code: '1'       # Fail workflow if HIGH/CRITICAL vulnerabilities found
          severity: 'HIGH,CRITICAL'

    # 5️⃣ Push Docker image

      - name: Push Docker image
        run: docker push srdeveloper9081/orthopedic-ai-app:latest1
